## 關於我的題目，我問老師

期間的性質 


老師認爲，比較偏向形成權，除斥期間



法律保留的類型

除斥期間


申報繳納義務的不作爲，是否是持續？

行爲的繼續？狀態的繼續？

不是除斥期間的概念

## W11_0502

問老師，是要先確認空污費是否法定之債，從而確認【期間】的性質是【公法上請求權消滅時效】或【除斥期間】，再通過對於現行法律規範做出評析、嗎？

老師：都有，這是一個實務、學説、立法互動的過程

## W12_0508

拿黃茂榮老師的課本中講到稅捐是法定之債的部分去問老師：稅捐是法定之債，爲何是稅捐法定主義（憲法23、19）的内容？

老師回答：我國稅法并未對於稅捐做明確的定義。所謂稅捐是法定之債，是學者直接依據德國的稅法中對於稅捐的定義，直接搬來在台灣的稅法而適用。所以，稅捐是依其定義而為法定之債。

所以，只有稅捐是法定之債？其他的公課都不是法定之債？

老師認爲，特別公課因爲其具有管制性質，應該需要一個行政處分去形成這樣的公法上權利義務關係。

---

## W12_0509

【老師改變想法了】

問老師：依照老師的文章，特別公課和稅捐的區別，主要是在於是否有群體共益性、群體有責性，那麽這樣的區別就導致稅捐是法定之債，而特別公課不是，這樣的差異，這是合理的嗎？爲什麽

老師答：對於特別公課是不是法定之債，我不能下定論。德國似乎也沒有很多針對問題的討論。僅僅憑藉管轄法院的區別（稅捐是財稅法院，特別公課是行政法院）而認定是否法定之債，是不足夠的。

但可以認爲特別公課與稅捐，應該性質接近。若做出只有稅捐是法定之債，這樣的區別，似乎不太合理。

在文章中，可以假設稅捐是法定之債。

## W13_0516

我認爲，主管機關的不同，不足以讓特別公課和稅捐有是否【法定之債】的性質的不同。

如果稅捐是法定之債，而特別公課就不是法定之債，這樣的差異，在法律效果上會導致稽徵程序的不同，

而氣候變遷因應條例，其中保留了未來課徵碳費、碳稅的授權。費、和稅，應該只是主管機關、法律形式上的區別，不應該有【是否法定之債】的差異。否則會造成不平等的法律適用結果。

老師：認同，兩者的性質上的趨近，應該符合平等原則的

要用怎麽樣的理由，去支持所謂的特別公課的【法定之債】的性質？

老師：依據特別公課與稅捐的接近。他們的性質上應該是趨近的。

特別公課與稅捐的差異不足以導致他們在是否【法定之債】的性質上面的差異。

且空污費之申報繳納，并不待一個行政處分的做成。

問老師：空氣污染防治費可以當作論文的題目嗎？

老師：當然，不然你花那麽多時間考慮這個問題？！
（XD