# W02_0228

連假



# W03_0307

劉致賢

論溢繳稅款返還請求權
——論2021年稅捐稽徵法28條之修正

法律性質：公法上的不當得利

2021年稽徵法28條修正



時效修正之不當
依據修法理由，有分別對於行政法、與民法之參考，





## 老師評

非常典型的主題式的報告


    第 28 條

    1. 因適用法令、認定事實、計算或其他原因之錯誤，致溢繳稅款者，納稅義務人得自繳納之日起十年內提出具體證明，申請退還；屆期未申請者，不得再行申請。但因可歸責於政府機關之錯誤，致溢繳稅款者，其退稅請求權自繳納之日起十五年間不行使而消滅。
    2. 稅捐稽徵機關於前項規定期間內知有錯誤原因者，應自知有錯誤原因之日起二年內查明退還。
    3. 納稅義務人對核定稅捐處分不服，依法提起行政救濟，經行政法院實體判決確定者，不適用前二項規定。
    4. 第一項規定溢繳之稅款，納稅義務人以現金繳納者，應自其繳納該項稅款之日起，至填發收入退還書或國庫支票之日止，按溢繳之稅額，依各年度一月一日郵政儲金一年期定期儲金固定利率，按日加計利息，一併退還。
    5. 中華民國一百十年十一月三十日修正之本條文施行時，因修正施行前第一項事由致溢繳稅款，尚未逾五年之申請退還期間者，適用修正施行後之第一項本文規定；因修正施行前第二項事由致溢繳稅款者，應自修正施行之日起十五年內申請退還。
    6. 中華民國一百十年十一月三十日修正之本條文施行前，因修正施行前第一項或第二項事由致溢繳稅款者，於修正施行後申請退還，或於修正施行前已申請尚未退還或已退還尚未確定案件，適用第四項規定加計利息一併退還。但修正施行前之規定有利於納稅義務人者，適用修正施行前之規定。
    7. 行為人明知無納稅義務，違反稅法或其他法律規定所繳納之款項，不得依第一項規定請求返還。

副標題寫：兼評，更符合論文的討論内容


修法前，完全沒有時效的規定，

期間、起算時間點

    行政程序法  
    第 128 條

    1. 行政處分於法定救濟期間經過後，具有下列各款情形之一者，相對人或利害關係人得向行政機關申請撤銷、廢止或變更之。但相對人或利害關係人因重大過失而未能在行政程序或救濟程序中主張其事由者，不在此限：
        一、具有持續效力之行政處分所依據之事實事後發生有利於相對人或利害關係人之變更者。
        二、發生新事實或發現新證據者，但以如經斟酌可受較有利益之處分者為限。
        三、其他具有相當於行政訴訟法所定再審事由且足以影響行政處分者。
    2. 前項申請，應自法定救濟期間經過後三個月內為之；其事由發生在後或知悉在後者，自發生或知悉時起算。但自法定救濟期間經過後已逾五年者，不得申請。
    3. 第一項之新證據，指處分作成前已存在或成立而未及調查斟酌，及處分作成後始存在或成立之證據。


具體知悉之時間點，在具體證明上不太容易

如果是申報納稅，那就是沒有行政處分，
明知無稅捐義務，仍繳納（配合相對人逃漏營業稅，貼用印花稅）


    民法 第 180 條

    給付，有左列情形之一者，不得請求返還：
        一、給付係履行道德上之義務者。
        二、債務人於未到期之債務因清償而為給付者。
        三、因清償債務而為給付，於給付時明知無給付之義務者。
        四、因不法之原因而為給付者。但不法之原因僅於受領人一方存在時，不在此限。


老師指導研究生，覺得條文不對，要提出建設性的看法，提供修法建議，立法實務、行政實務

立法修正的格式（三欄）

修正條文、現行條文、説明


鼓勵大家發表，有稿費的，但是稿費不是重點，發表才是重點，稿費只是附帶利益


最佳稅法判決，[選輯](https://www.pwc.tw/zh/publications/topic-tax/2022-bestcase.html)

從葛老師開始做，每年選出一些判決

也不是一定要批評法院，用語上盡量和緩，有自己的看法，別人也有其他的想法

老師比較傾向，適當地表達觀點，讓個案法官瞭解。

很多其實是法律立法的不妥當，立法理由的不妥當

判決評釋，有字號，做成的法官，也會看，
