
# 110年度上字第740號

W04_0314

老師評

## 事實整理【凡是重要的爭議事實】

上訴人101、102及105年度綜合所得稅結算申報，於列舉扣除額項下列報：

㈠101年度部分：上訴人配偶林茂昌於民國101年10月8日與華南商業銀行受託殷商慈善教育公益信託基金專戶（下稱華南銀行受託公益信託專戶）簽訂贈與契約書，約定贈與新漢股份有限公司（已上櫃，原名稱為新漢電腦股份有限公司，於103年7月24日變更名稱為新漢股份有限公司，下稱新漢公司）股票150,000股，當日收盤價新臺幣（下同）**27.55元**；
上訴人於101年10月23日與財團法人稻馨教育基金會（下稱稻馨基金會）簽訂贈與契約書，約定贈與新漢公司股票68,000股，當日收盤價**26.5元**之捐贈扣除額（下稱非現金捐贈扣除額）5,889,665元

【（捐贈上限：綜合所得總額31,953,328元×20％－現金捐贈501,000元＝5,889,665元）<5,934,500元＝（150,000股×**27.55元**）＋（68,000股×**26.5元**）】；

㈡102年度部分：上訴人及林茂昌於102年6月27日與華南銀行受託公益信託專戶簽訂贈與契約書，約定贈與新漢公司股票43,000股及122,000股，當日收盤價**26.85元**；
另於102年8月5日與華南銀行受託公益信託專戶簽訂贈與契約書，分別約定贈與該公司股票14,000股及52,000股，當日收盤價**28.2元**之非現金捐贈扣除額6,260,934元

【（捐贈上限：綜合所得總額31,472,170元×20％－現金捐贈33,500元＝6,260,934元）<6,291,450元＝（43,000股＋122,000股）×26.85元＋（14,000股＋52,000股）×28.2元】；

㈢105年度部分：上訴人及林茂昌於105年9月23日與華南銀行受託公益信託專戶簽訂贈與契約書，分別約定贈與新漢公司股票51,000股及68,000股，當日收盤價**38.25元**之非現金捐贈扣除額4,391,083元

【（捐贈上限：綜合所得總額21,955,418元×20％＝4,391,083元）<4,551,750元＝（51,000股×**38.25元**）＋（68,000股×**38.25元**）】（按前揭上訴人及林茂昌捐贈之新漢公司股票，下綜稱系爭股票）。


被上訴人依據查得資料，以上訴人及林茂昌：
㈠101年度部分：

於101年10月8日贈與新漢公司股票150,000股予華南銀行受託公益信託專戶，惟於101年12月22日（收盤價**24.3元**）始轉讓股票；
上訴人於101年10月23日贈與新漢公司股票68,000股予稻馨基金會，惟於101年12月6日（收盤價**25.2元**）始轉讓股票，按實際轉讓股票日之收盤價核算非現金捐贈扣除額5,358,600元【（150,000股×24.3元）＋（68,000股×25.2元）】，核定綜合所得總額31,953,328元，綜合所得淨額25,306,895元，應補徵稅額212,426元。

㈡102年度部分：

於102年6月27日贈與新漢公司股票43,000股及122,000股予華南銀行受託公益信託專戶；
另於102年8月5日贈與新漢公司股票14,000股及52,000股予同信託專戶，惟於102年9月11日及12日（收盤價**23元及22.95元**）始轉讓股票，按實際轉讓股票日之收盤價核算非現金捐贈扣除額5,310,150元【（43,000股×22.95元）＋（122,000股×23元）＋（14,000股×22.95元）＋（52,000股×23元）】，核定綜合所得總額331,472,170元，綜合所得淨額24,984,876元，應補徵稅額380,313元。

㈢105年度部分：

於105年9月23日贈與新漢公司股票51,000股及68,000股予華南銀行受託公益信託專戶，惟於105年11月17日及22日（收盤價29.9元及30.3元）始轉讓股票，按實際轉讓股票日之收盤價核算非現金捐贈扣除額3,578,500元【（51,000股×30.3元）＋（68,000股×29.9元）】，核定綜合所得總額21,955,418元，綜合所得淨額17,210,473元，應補徵稅額325,033元。上訴人循序提起行政訴訟，聲明請求判決訴願決定、復查決定及原處分均撤銷。經原審以原判決駁回。上訴人仍不服，提起本件上訴，聲明請求原判決廢棄，訴願決定、復查決定及原處分均撤銷。


被集中保管的有價證券

究竟應該依據債、物（申請轉換日、實際劃撥日（受捐贈者實際取得股權））


國稅局所認定之實際


> 所得稅法第13條規定：
「個人之綜合所得稅，就個人綜合所得總額，減除免稅額及扣除額後之綜合所得淨額計徵之。」第17條第1項第2款第2目之1規定：「按第14條至第14條之2及前2條規定計得之個人綜合所得總額，減除下列免稅額及扣除額後之餘額，為個人之綜合所得淨額：……扣除額：納稅義務人就下列標準扣除額或列舉扣除額擇一減除外，並減除特別扣除額：㈠……㈡列舉扣除額：1.捐贈：納稅義務人、配偶及受扶養親屬對於教育、文化、公益、慈善機構或團體之捐贈總額最高不超過綜合所得總額百分之20為限。但有關國防、勞軍之捐贈及對政府之捐獻，不受金額之限制。


## 老師評論

本件判決，不需要撤銷發回，只需要就原判決判決理由寫錯的部分重判就好了！


本件個案的重點：是在於捐贈扣除額的上限與捐贈股票之價值認定之對應關係


爲什麽捐贈列舉扣除額度有20% 的上限？

稅捐優惠！立法者有寬廣的立法形成空間。

非現金捐贈，有可能會有價值認定的可能，會不會被灌水？
（捐贈勞務？捐贈工程？）

以取得之成本作爲價值認定之標準

如果以市場價值去評價？（市場價值可能會形成强迫推銷給國稅局，强迫國稅局接受某一市場價值）

> 德國，非現金給付的形態，要明文規定（世界名畫、名人手稿手跡

所得基本稅額條例，非現金捐贈之額度，又重新拉回來。

老師：原則上，非現金捐贈，不可以，如果要，就要以成本價認定！

- 股票捐贈——是直接按收盤日的價格（財政部訂定標準，關於非現金捐贈【個人以非現金財產捐贈列報扣除金額之計算及認定標準】）



## 老師有機會要針對借名行爲討論

借名行爲、操控内外部關係


老師有針對借名行爲做過主題式的探討。

在西方社會比較少出現，但是在華人世界常見

在民事法、稅法等領域具有不同的討論價值


