# 臺北高等行政法院110年訴字第1374號判決 —— 老師的判決評釋

W05_0321

- 裁判字號：[臺北高等行政法院110年訴字第1374號判決](https://www.lawsnote.com/judgement/62c5ac7d8b4ccbb5c0caa34e?t=2940203042) 
- 裁判日期：民國111年06月30日
- 裁判案由：房屋稅

## 程序 

### 判決主文

> 訴願決定及原處分（即復查決定）均撤銷。

沒有撤銷到核課處分？

行政訴訟，的訴訟標的理論

c.f.

- 訴訟標的
  - **行政處分**的違法性和侵害（相對人）納稅義務人的權利（及法律上應受保護的利益）性
- 程序標的
  - **行政處分**（提起救濟程序的對象）
    - 1. 核課處分
    - 2. 復查處分（決定）
    - 3. 訴願處分（決定）
    - （4. 訴訟）
    - 爲什麽法院的判決處分？
      - 怕逾越核課期間
      - 僅僅讓他重為復查決定
      - 111年6月30
        - 此時SJF已經修正了21T3X規定
        - 現在已經有了【時效不完成制度】
        - 核課處分一旦被撤銷，自始不生效力，但是依據21T3X規定，還有1年的期間
        - 本件，【既然已經有時效不完成的制度了】，就應該把原處分一并撤銷！不然，只撤銷到復查，又是以前的【萬年稅單】了
    - 法院應該：訴願決定及原處分（即原核課處分及復查決定）均撤銷。
      - 撤銷原核課處分
      - 行政機關依判決重新做成核課處分
        - 如果納稅義務人還不服
          - 不用再經過【很折磨的】訴訟前置程序（訴願+復查）
          - 就直接在原審法院提起救濟

### 【查對更正】替代【復查程序】

復查



<button type="button" class="collapsible">稅捐稽徵法 第 17 條</button>
<div class="content">
  <p>
納稅義務人如發現繳納通知文書有記載、計算錯誤或重複時，於規定繳納期間內，得要求稅捐稽徵機關，**查對更正**。  
  </p>
</div>
<br>

> 稅捐稽徵法 第 17 條
> 納稅義務人如發現繳納通知文書有記載、計算錯誤或重複時，於規定繳納期間內，得要求稅捐稽徵機關，**查對更正**。
>

查對更正：明顯的錯誤，才可以

稅捐稽徵實務，經常濫用，將SJF17T當作回應復查（對核課處分的不服）
其實是實際上改變了原先做成的核課處分

爲什麽不可以？

- 復查：【不利益變更禁止原則】的適用（【最高行的前身行政法院的判例：】基於行政訴訟程序的法理）？
- 但其實復查是行政機關做成的行政程序，從而，復查和訴願（80）是不受不利益變更禁止原則】的拘束，
- 是最高行自己弄錯，以爲復查程序受【不利益變更禁止原則】的適用

而實務上【查對更正】可以規避【不利益變更禁止】的拘束

> 怎麽講誰對誰錯？這就是法治的亂七八糟的狀態


## 實體

### 房屋稅稅基，稅率 正當性

基於事物的觀察，評價【房屋】所應該有的價值

這種評價判斷可能不是邏輯，其適當與否屬於立法形成空間。

原則上，司法是加以尊重的

> 房屋稅條例 
> 
> 第 11 條
> 房屋標準價格，由不動產評價委員會依據下列事項分別評定，並由直轄市、縣（市）政府公告之：
> 一、按各種建造材料所建房屋，區分種類及等級。
> 二、各類房屋之耐用年數及折舊標準。
> 三、按房屋所處街道村里之商業交通情形及房屋之供求概況，並比較各該不同地段之房屋買賣價格減除地價部分，訂定標準。
> 前項房屋標準價格，每三年重行評定一次，並應依其耐用年數予以折舊，按年遞減其價格。
> 
> 第 5 條
> 房屋稅依房屋現值，按下列稅率課徵之：
> 一、住家用房屋：供自住或公益出租人出租使用者，為其房屋現值百分之一點二；其他供住家用者，最低不得少於其房屋現值百分之一點五，最高不得超過百分之三點六。各地方政府得視所有權人持有房屋戶數訂定差別稅率。
> 二、非住家用房屋：供營業、私人醫院、診所或自由職業事務所使用者，最低不得少於其房屋現值百分之三，最高不得超過百分之五；供人民團體等非營業使用者，最低不得少於其房屋現值百分之一點五，最高不得超過百分之二點五。
> 三、房屋同時作住家及非住家用者，應以實際使用面積，分別按住家用或非住家用稅率，課徵房屋稅。但非住家用者，課稅面積最低不得少於全部面積六分之一。
> 前項第一款供自住及公益出租人出租使用之認定標準，由財政部定之。

- 稅基考量因素
  1. 折舊
  2. 建材標準單價表
     1. 材料越堅固的，折舊年限越長
  3. 地段（區段域）
- 稅率
  1. 用途

這三個因素，是不是適當的考量因素？

- 曾有（某團體）一種觀點：
  - 房屋只會越來越舊，理論上（事物之本質、財務會計之觀點），越來越老，只會越來越不值錢
  - 房屋稅考慮地段，跟地價稅考慮地段是重複考量，構成重複課稅
  - 爲什麽房屋稅越來越高，都是因爲地段的考量

【老師】：同一建商、同一時間、同一建材、同一商業用途，而處於不同地段，房屋價值是否一樣？

房屋就是跟土地不能分開來

德國，房地合一，不動產的財產稅的估價：有建築的土地、無建築的土地，針對土地的評價

德國民法的不動產只有一種，只有土地：有建築的土地、沒有建築的土地

台灣的民法學日本：房屋、土地分開來

> 我們的立法者不當地將土地和房屋拆分，變成2個，造成稅基的破碎和切割，違反平等原則，任意性切割！
> 房地本來就不應該分開
> 坐落地就是會影響土地、房屋的價值——客觀現實

憲法：土地增值稅143T3X

不動產的移轉交易所得稅，也是符合憲法143T3X的意旨的

### 桃園市相關調整之正當性

本件個案爭議點所在

桃園市房屋地段等級表暨桃園市房屋街道等級調整率表（下稱房屋地段調整率表）第3點第3項規定，

針對同樣位在噪音防制區內的系爭房屋取消30％的房屋稅減免，明顯違反平等原則。

桃園市簡化評定房屋標準價格及房屋現值作業要點（下稱簡化評定要點）

同樣坐落在航道之下：

- 地段率
  - 別人的地段率：70%
  - 桃機的房屋的地段率：100%
- 建材標準單價表
  - 別人的：default
  - 桃機：200%

國際機場園區發展條例

> 國際機場園區發展條例
>
> 第 18 條
> 
> 1. 民航局經管園區之財產，除公有土地依第十一條第二項規定辦理外，其餘財產得以出租、作價投資方式，提供機場公司使用，不受國有財產法第二十八條及地方公產管理法令之限制。
> 2. 第三人於本條例施行前，與民航局及所屬機關（構）就經管園區資產已簽訂之契約，由機場公司自成立之日起繼受之。
> 
> 第 21 條
> 
> 1. 機場公司依第十三條規定收取之使用費、服務費及依第十五條規定收取之機場服務費，準用加值型及非加值型營業稅法第八條免徵營業稅及申請放棄適用免稅之規定。
> 2. 機場公司依第十一條第一項規定取得直接供航空器起飛、降落與地面活動區域及供公共使用之機場專用區土地，免納地價稅。民航局依第十一條第二項規定提供機場公司於機場專用區使用之公有土地，亦免納地價稅。
> 3. **機場公司依第十八條第一項規定作價投資取得或自行於機場專用區興建之建築物，除提供第三人使用並為收益者外，免納房屋稅**。
>

> SDSF4T1X
> 1. 下列各種所得，免納所得稅：
> 
> 十八、各級政府機關之各種所得。
> 十九、各級政府公有事業之所得。
>

18：同樣是高權機關
19：公有事業：公法上任務的所得

### 公有事業房屋稅免徵

桃機航空公司

事實上是法律中是給付行政之一環，以私法組織之形式做公法任務之完成

理論上來講，是公有事業

所以應該細節地去厘清是否有國際機場園區發展條例第 21 條第3項本文之適用

老師：如果是法官：如果房屋是做公共使用：直接撤銷，沒有再有課稅處分
如果一定要做另外的課稅處分，也是在法院自己算，直接做成核課處分，不要再撤銷發回，盡量一個審級就處理完。



