# W06_0328

借名行爲

臺北高等行政法院判決
111年度訴字第194號

原告102年度綜合所得稅結算申報，經被告依據通報及查得資料，臺北市內湖區潭美段3小段933、934及934-2地號土地(下稱潭美段3筆土地)經臺北市政府為一般徵收，發放徵收補償費予訴外人楊有吉，嗣臺北市政府撤銷一般徵收，改為區段徵收，原先地主領取之徵收補償金應繳回政府，原告以代楊有吉繳回徵收補償費為代價，取得潭美段3筆土地，並將土地借名登記於**陳敏惠**（原告配偶陳麗美之胞妹）名下。

潭美段3筆土地經區段徵收後，**地主於88年8月26日領回抵價地**(即臺北市內湖區安康段5-3地號土地、持分29,851／100,000，登記所有權人為陳敏惠。下稱系爭土地)，系爭土地嗣於102年12月11日出售予荃揚實業有限公司(下稱荃揚公司)，原告應受分配40,252,283元，扣除取得成本(即代楊有吉繳回徵收補償費)2,378,579元、出售時土地增值稅841,127元，核定其他所得37,032,577元(40,252,283－2,378,579－841,127)，乃併課核定原告102年度綜合所得總額38,156,173元，補徵應納稅額14,232,456元，並按所漏稅額14,232,456元處0.5倍之罰鍰7,116,228元。

原告不服，申請復查，獲追減其他所得170,776元（印花稅4,094元、仲介費及信託管理費166,682元）及罰鍰34,155元。原告仍不服，提起訴願仍遭駁回，遂提起本件行政訴訟。

取得土地：88年8月26日領回抵價地

出售土地：102年12月11日

原告於103年5月22日辦理102年度綜合所得稅結算申報（遵期申報）

核課期間（7年）至110年5月21日屆滿（申報即時起算5年：108年5月21）

本件核定通知書及繳款書業於109年8月10日合法送達，並未逾核課期間。

核課期間：

- SJF21T1X1K：5年
- SJF21T1X3K：7年
  - SJF49T1X：裁罰准用


原告土地登記請求權實現之利益：




> 次按最高行政法院101年度4月份第2次庭長法官聯席會議決議：「購買土地未辦竣所有權移轉登記，依民法第758條第1項規定，並未取得土地所有權，非土地所有權人，其再行出售該土地，使原出賣人直接移轉登記為新買受人所有，因其未受土地增值稅之核課，縱被依土地稅法第54條第2項及平均地權條例第81條規定處罰，仍非屬土地所有權人出售土地，因此所獲增益，非屬所得稅法第4條第1項第16款所稱之『出售土地』之交易所得，自不得免納所得稅。」

跟土地有關的所得，但不是第4條第1項第16款個人出售土地之免稅所得，屬於：應屬所得稅法第14條第1項第10類其他所得之收入額

SJF

> 
> 第 21 條
> 
> 1. 稅捐之核課期間，依下列規定：
> 一、依法應由納稅義務人申報繳納之稅捐，已在規定期間內申報，且無故意以詐欺或其他不正當方法逃漏稅捐者，其核課期間為五年。
> 二、依法應由納稅義務人實貼之印花稅，及應由稅捐稽徵機關依稅籍底冊或查得資料核定課徵之稅捐，其核課期間為五年。
> 三、**未於規定期間內申報，或故意以詐欺或其他不正當方法逃漏稅捐者**，其核課期間為七年。
>
> 第 41 條
> 
> 1.納稅義務人**以詐術或其他不正當方法逃漏稅捐者**，處五年以下有期徒刑，併科新臺幣一千萬元以下罰金。
> 2. 犯前項之罪，個人逃漏稅額在新臺幣一千萬元以上，營利事業逃漏稅額在新臺幣五千萬元以上者，處一年以上七年以下有期徒刑，併科新臺幣一千萬元以上一億元以下罰金。
> 

SJF21T1X3K 未盡誠實申報之作爲義務（誠實、及時、完全）：

- **未於規定期間內申報，或故意以詐欺或其他不正當方法逃漏稅捐者**
  - 匿報（隱匿事實）、短報（收入數額）、漏報【積極作爲】
  - 未申報【消極不作爲】:**未於規定期間內申報**

又稅捐稽徵法第41條漏稅罪，係屬作為犯，而非不作為犯，即須以詐術或其他不正當方法之作為，以逃漏稅捐，始克成立，為最高法院70年台上字第6856號判例所明示，此與稅捐稽徵法第21條第1項第3款包含以消極不作為之不正當方法逃漏稅捐者尚屬有別（最高行政法院107年度判字第435號判決參照）

老師：最高法院其實是錯了！是胡説八道
老師文章：行為罰、漏稅罰與逃漏稅捐罪－評司法院大法官釋字第五○三號解釋


不作爲、作爲都應該適用SJF41T

## 借名行爲

- 借牌
  - 借牌營業、借牌投標
- 借賬戶
  - 銀行匯款、證券期貨市場
- 借登記
  

借名登記：

- 物權行爲
- 債權契約【私法自治】

老師以前學的時候是無權處分+善意取得，
後來變成有權取得，就算是惡意的第三人，跟借用他人名義的人，到底是誰比較值得保護？
借用他人名義，就要承擔這樣的風險！

這兩個之間有沒有矛盾？内部有效，外部也有效！


- 如果是連帶債務人，那麽會使土地增值稅的連帶，還是所得稅的連帶

沒有登記為所有權人，就不是土地增值稅

> 台灣的法治把土地增值的所得拉出來變成土地增值稅就是胡搞瞎搞的稅制，
> 分拆稅基，怎麽會符合平等原則、量能課稅


根本就是違反憲法的


借名關係，類似於隱名合夥關係

有人出錢，有人出名


